# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "static"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  # [[redirects]]
  #   from = "/img/*"
  #   to = "/static/img/:splat"
  #   status = 200
  # [[redirects]]
  #   from = "/vendor/*"
  #   to = "/static/vendor/:splat"
  # [[redirects]]
  #   from = "/web_modules/*"
  #   to = "/static/web_modules/:splat"
  #   status = 200
  [[redirects]]
    from = "/*"
    to = "/.netlify/functions/sapper/:splat"
    status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  [dev]
   publish = "static" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
